name: "Build and Publish to ECR"
description: "Builds and Pushes built artifacts to ECT"

inputs:
  node-version:
    description: "The version of node to use"
    required: false
    default: "12.x"

  npm-token:
    description: "npm credentials, most useful for private repositories"
    required: true

  skip-db-setup:
    description: "Set to false if db setup is required"
    required: false
    default: true

  skip-test:
    description: "Set to true if building for deploy"
    required: false
    default: false

  skip-lint:
    description: "Set to true if lint is not required/supported/needed"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Set the BARE_SERVICE_NAME environment variable
      shell: bash
      run: |
        echo BARE_SERVICE_NAME=$(node -p -e "require('./package.json').name.replace(/^@gasbuddy\//,'')") >> $GITHUB_ENV

    - name: npm install
      shell: bash
      run: |
        npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        npm install
      env:
        NPM_TOKEN: ${{inputs.npm-token}}

    - name: Set up db
      shell: bash
      run: |
        echo "Creating application database ..."
        npm run db:ci
        npm run db:dev
      if: ${{ inputs.skip-db-setup != 'true' }}

    - run: npm run lint
      shell: bash
      if: ${{ inputs.skip-lint != 'true' }}

    - run: npm run build
      shell: bash

    - run: npm run ci-test
      shell: bash
      if: ${{ inputs.skip-test != 'true' }}
