name: "Build and Publish to ECR"
description: "Builds and Pushes built artifacts to ECT"

inputs:
  node-version:
    description: "The version of node to use"
    required: false
    default: "12.x"

  npm-token:
    description: "npm credentials, most useful for private repositories"
    required: true

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}

    - name: npm install
      shell: bash
      run: |
        npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        npm install
      env:
        NPM_TOKEN: ${{inputs.npm-token}}

    - run: npm run lint
      shell: bash

    - run: npm run build
      shell: bash

    - run: npm run ci-test
      shell: bash
